apiVersion: v1
kind: Service
metadata:
  name: offsec-portal-ext
  labels:
    app: offsec-portal-ext
spec:
  selector:
    app: offsec-portal-ext
  ports:
    - name: http
      port: 9115
      targetPort: 9115
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: offsec-ui
  labels:
    app: offsec-ui
spec:
  selector:
    app: offsec-ui
  ports:
    - name: http
      port: 3001
      targetPort: 3000
  type: ClusterIP
